version: '3.8'

services:
  test-runner:
    build:
      context: .
    entrypoint: ["flake8", "."]
    
  fastapi:
    build:
      context: .  # Change to `app` if `Dockerfile` is inside `app/`
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=your-database-url
    volumes:
      - ./app:/app
    networks:
      - app-network

  celery:
    build:
      context: .  # Change to `app` if `Dockerfile` is inside `app/`
      dockerfile: Dockerfile
    container_name: celery-worker
    command: celery -A app.celery worker --loglevel=info
    environment:
      - DATABASE_URL=your-database-url
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
