
services:
  fastapi:
    image: sydulamin/test-python-app:${COMMIT_HASH:-latest}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
    restart: on-failure:10
    healthcheck:
      test: curl --fail http://localhost:8000/health
      start_period: 2s
    networks:
      - app-network

networks:
  app-network: