version: '3.8'

services:
  test-runner:
    build:
      context: app
    entrypoint: ["flack8"]

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=your-database-url
    volumes:
      - .:/app
    networks:
      - app-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-worker
    command: celery -A your_project_name.celery worker --loglevel=info
    environment:
      - DATABASE_URL=your-database-url
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
