name: Docker CI/CD
description: Docker CI/CD pipeline for building and deploying Docker images to Docker Hub
on:
  push:
    branches:
      - "main"

env:
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  DOCKERHUB_REPOSITORY_NAME: test-python-app

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0  # Ensure all files are fetched

            - name: Debug file structure
              run: ls -R  # Print files and folders

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ env.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v3
              with:
                images: |
                    ${{ env.DOCKER_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY_NAME }}
                tags: |
                    type=sha,prefix=,suffix=

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .  # Change to "." if Dockerfile is in root
                push: true
                tags: ${{ steps.meta.outputs.tags }}
