name: Build and Deploy
description: Docker CI/CD pipeline for building and deploying Docker images to Docker Hub
on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  
  DOCKERHUB_REPOSITORY_NAME: test-python-app
  DEPLOYMENT_SERVER_IP: ${{ secrets.INSTANCE_IP }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/my-image
          tags: type=sha,prefix=,suffix=

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .  
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Transfer Docker compose file to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.DEPLOYMENT_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.INSTANCE_RSA_PRIVATE_KEY }}
          source: "docker-compose.production.yaml"
          target: "~/"

      - name: Deploy application using Docker Compose
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ env.DEPLOYMENT_SERVER_IP }}
          username: ubuntu
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            [your-private-key-content]
            -----END OPENSSH PRIVATE KEY-----
          script: |
            export COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-7)
            docker compose -f ~/docker-compose.production.yaml up -d
