name: Main Branch CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pylint pytest safety

      - name: Lint Check
        run: flake8 . --count --show-source --statistics

      - name: Code Quality Check
        run: pylint $(git ls-files '*.py')

      - name: Run Unit Tests
        run: pytest --junitxml=reports/unit-test-results.xml

      - name: Dependency Security Check
        run: safety check

      # - name: Dockerfile Linting
      #   run: |
      #     wget -qO- https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64 -O /usr/local/bin/hadolint
      #     chmod +x /usr/local/bin/hadolint
      #     hadolint Dockerfile

      - name: Build Docker Image
        run: |
          docker build -t my-slim-image:latest .

      - name: Verify Docker Image
        run: |
          docker run --rm my-slim-image:latest python test.py
