name: Release Pipeline

on:
  release:
    types:
      - created

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code at the current release
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (for multi-platform builds if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the final Docker image
      - name: Build Docker Image
        run: |
          docker build -t sydulamin/my-slim-image:${{ github.event.release.tag_name }} .

      # Push the Docker image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push sydulamin/my-slim-image:${{ github.event.release.tag_name }}
